name: roofpedia-cpu-new
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.8
  - pip
  - geopandas
  - matplotlib
  - pillow
  - libwebp
  - toml
  - tqdm
  - pytorch
  - torchvision
  - pyproj=3.4.1
  - pip:
      - mercantile==1.0.4
      - opencv-python
      - geojson
